### ISSUE TITLE
An Issue about RSPNVPK

### ISSUE THREAD

**Issue by SakuraSayaka** [squidgyberries/coppermod#1]
I'm sorry, this is an issue for RSPNVPK, but I can't add an issue to that project.
Does RSPNVPK support, or will it support, using the command line to make edits to vpk files? I would like to use a batch file to install mods for other people, but none of the vpktool's that came before it support using the command line.

**Comment by squidgyberries** [comment]
Yes, it does support using it from the command line just specify the vpk as the first argument, you can also specify a `-s` argument after it to be silent and not ask for user confirmation.

The pre built binaries also have `-nb` for no backup but the source code version doesn't even make a backup because that repo is a mess. But I'm currently working on a rewrite that will have more features and hopefully not be as messy.

**Comment by SakuraSayaka** [comment]
Thanks! So is there a way to specify the location of a folder? I want to separate the folders from the vpk files, instead of having to put them in the same directory.
